### ISSUE TITLE
"Katipunero" Unit Too OP?

### ISSUE THREAD

**Issue by chris03-dev** [shannaurelle/ph-bonifacio-unciv#14]
Greetings. I have just read the details for the "Katipunero" unit, and I must say it's a bit overpowered.

Unique units have their own minor changes in terms of damage, defense, movement cost, promotions, or any other unique behavior. Typically this makes the unique units a slight upgrade or a sidegrade to its regular counterpart.

The "Katipunero" unit is anything but a "slight" upgrade. Katipuneros have both Shock I and what's basically a slightly nerfed Drill II (25% bonus on Hill, Forest, Jungle aka. "Rough Terrain") upon its creation, which is much more than expected for a unique unit.

I'd suggest that the unit should only have the Drill I promotion (they utilized guerilla warfare techniques by the the 1900s), and that it should cost less than a regular Rifleman in other civilizations, ideally between 1300 to 1500 (please correct me if I was mistaken, but I think they were generally ill-equipped against enemy forces).

Thanks for reading my suggestion.

**Comment by shannaurelle** [comment]
Thank you for taking your time in writing this message.

Upon further examination in the historical records, I will partly consider your recommendations. I will weaken the base strength of the Unique Unit from 34 to 28, reduce the production cost from 225 to 180, and replace the rough terrain bonus and Shock I with Woodsman.  This should make the unit slightly weaker against all Riflemen variants while making it easier to produce, and Woodsman should reflect its ability to conduct guerilla warfare. I hope this may be satisfactory to you.

**Comment by chris03-dev** [comment]
I think that's good enough for me! Thank you for the attention on this issue.
